ktor {
  development = true
  deployment {
    port = 8080
    watch = [classes]
  }

  application {
    modules = [at.tfro.sonic_link.server.ApplicationKt.module]
  }

  media {
    library {
      folder = "/home/fromml/Projects/SonicLink/server/media/library"
    }
    triage {
      folder = "/home/fromml/Projects/SonicLink/server/media/triage"
    }
  }
}

data {
  dir = "/home/fromml/Projects/SonicLink/server/data"
}