---
name: Build and Release Docker Image

on:
  push:
    branches: [ci_prod]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |-
          IMAGE=ghcr.io/fromwau/soniclink:ci_prod
          docker build -t $IMAGE .
          docker push $IMAGE
